[package]
name = "radical_red_dex"
version = "0.1.0"
edition = "2021"
author = "[vodiniz <vitor.oliveira.vod@gmail.com>]"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

calamine = "0.18.0"
pokerust = "0.2.0"
owo-colors = "3.2.0"
